config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :rooms, only: [:new, :create, :destroy] do
    resources :posts, only: [:index, :new, :create] do
      member do
        get 'show_image/:index', to: 'posts#show_image', as: 'show_image'
        get 'show_video/:index', to: 'posts#show_video', as: 'show_video'
        delete 'show_image/:index/image', to: 'posts#destroy_image', as: 'destroy_image'
        delete 'show_video/:index/video', to: 'posts#destroy_video', as: 'destroy_video'
        post 'add_favorite/:index/:media_type', to: 'favorites#create', as: 'add_favorite'
        delete 'remove_favorite/:index/:media_type', to: 'favorites#destroy', as: 'remove_favorite'
      end
    end
    member do
      delete 'exit'
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: :show do
    get '/download_favorites.zip', to: 'favorites#download_all', as: 'download_favorites'
    resources :favorites, only: :index
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_room,   only: [:create, :destroy]
  before_action :set_post,   only: [:create, :destroy]
  before_action :set_media,  only: [:create, :destroy]
  include Zipline

  def index
    @page_title = "Favorite"
    @favorites = current_user.favorites.includes(:post).order("created_at DESC")
  end

  def create
    favorite = current_user.favorites.build(post_id: @post.id, room_id: @room.id, media_id: @media_index, media_type: @media_type)
    if favorite.save
      # respond_to do |format|
      #   format.js
      # end
      if @media_type == "image"
        redirect_to show_image_room_post_path(@room.id, @post.id, params[:index])
      else
        redirect_to show_video_room_post_path(@room.id, @post.id, params[:index])
      end
    end
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, post_id: @post.id, room_id: @room.id, media_id: @media_index, media_type: @media_type)
    if favorite.destroy
      # respond_to do |format|
      #   format.js
      # end
      if @media_type == "image"
        redirect_to show_image_room_post_path(@room.id, @post.id, params[:index])
      else
        redirect_to show_video_room_post_path(@room.id, @post.id, params[:index])
      end
    end
  end


  def download_all
    favorites = current_user.favorites

    respond_to do |format|
      format.zip do
        files = favorites.map do |favorite| 
          if favorite.media_type == "image"
            [favorite.post.images[favorite.media_id], "#{favorite.id}.jpg"]
          else
            [favorite.post.videos[favorite.media_id], "#{favorite.id}.mp4"]
          end
        end
        zipline(files, 'favorites.zip', auto_rename_duplicate_filenames: true)
      end
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_post
    @post = @room.posts.find(params[:id])
  end

  def set_media
    @media_index = params[:index].to_i
    @media_type = params[:media_type]
    if @media_type == 'image'
      @media = @post.images[@media_index]
    else
      @media = @post.videos[@media_index]
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? && post.favorited_by?(current_user, post, media_id, media_type)%>
  <%=link_to remove_favorite_room_post_path(room, post, media_id, media_type),  data: { turbo_method: :delete }, class: "post_favorites_on", remote: true do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
    </svg>
  <% end %>
<% else %>
  <%=link_to add_favorite_room_post_path(room, post, media_id, media_type),  data: { turbo_method: :post }, class: "post_favorites_off", remote: true do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
      <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
    </svg>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
document.getElementById('like-btn<%= @media.id %>').innerHTML = "<%= j(render partial: 'favorites/favorite', locals: {room: @room, post: @post, media_id: @media_index, media_type: @media_type}) %>"

app/views/favorites/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "posts/side-bar" %>
  </div>
  <div class="side-space"></div>

  <div class="header-mobile">
    <%= render 'shared/header'%>
  </div>
  
  <div class="main-contents">
    <div class="main-header">
      <div class="main-header-upper">
        <div class="main-header-upper_left">
          <div class="title-text">
            Favorite
          </div>
        </div>
        <div class="main-header-upper_right">
          <%= link_to "Download All", user_download_favorites_path(current_user), class: "btn btn-primary" %>
        </div>
      </div>
      <hr>
    </div>
    <div class="posts">
      <% @favorites.each do |favorite| %>
        <% if favorite.post.images.attached? || favorite.post.videos.attached? %>
          <% if favorite.media_type == "image" %>
            <div class="post">
              <%= link_to show_image_room_post_path(favorite.room_id, favorite.post, index: favorite.media_id) do %>
                <%= image_tag favorite.post.images[favorite.media_id].variant(resize_to_fill: [300, 300, gravity: 'center']).processed, class: 'img-thumbnail' %>
              <% end %>
            </div>
          <% else %>
            <div class="post">
              <%= link_to show_video_room_post_path(favorite.room_id, favorite.post, index: favorite.media_id) do %>
                <div class="video-background">
                  <% if favorite.post.videos[favorite.media_id].representable? %>
                    <%= image_tag favorite.post.videos[favorite.media_id].representation(resize_to_fill: [300, 300, gravity: 'center']).processed, class: 'img-thumbnail' %>
                    <%# <%= video_tag rails_blob_path(favorite.post.videos[favorite.media_id], disposition: :attachment), class: 'img-thumbnail' %>
                  <% end %>
                </div>
                <div class="video-icon">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="block" class="bi bi-caret-right-square-fill" viewBox="0 0 16 16">
                    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm5.5 10a.5.5 0 0 0 .832.374l4.5-4a.5.5 0 0 0 0-.748l-4.5-4A.5.5 0 0 0 5.5 4v8z"/>
                  </svg>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>  
    </div>
  </div>

  <div class="footer-mobile">
    <%= render 'shared/footer'%>
  </div>
</div>