config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :rooms, only: [:new, :create, :destroy] do
    resources :posts, only: [:index, :new, :create] do
      member do
        get 'show_image/:index', to: 'posts#show_image', as: 'show_image'
        get 'show_video/:index', to: 'posts#show_video', as: 'show_video'
        delete 'show_image/:index/image', to: 'posts#destroy_image', as: 'destroy_image'
        delete 'show_video/:index/video', to: 'posts#destroy_video', as: 'destroy_video'
        post 'add_favorite/:index/:media_type', to: 'favorites#create', as: 'add_favorite'
        delete 'remove_favorite/:index/:media_type', to: 'favorites#destroy', as: 'remove_favorite'
      end
    end
    member do
      delete 'exit'
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: :show do
    get '/download_favorites.zip', to: 'favorites#download_all', as: 'download_favorites'
    resources :favorites, only: :index
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-category">
    <%= link_to (user_path(current_user.id)), class: 'btn btn-outline-dark' do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
        <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z" />
      </svg>
    <% end %>
  </div>

  <div class="footer-category">
    <div class="dropup-center dropup">
      <button class="btn btn-outline-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box" viewBox="0 0 16 16">
          <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
        </svg>
      </button>
      <ul class="dropdown-menu">
        <% current_user.rooms.each do |room| %>
          <li>
            <%= link_to(room_posts_path(room), class: 'dropdown-item') do %>
              <%= room.name %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="footer-category">
    <%= link_to user_favorites_path(current_user), class: 'btn btn-outline-dark' do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
      </svg>
    <% end %>
  </div>

  <div class="footer-category">
    <div class="dropup-center dropup">
      <button class="btn btn-outline-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
          <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to 'New room...', new_room_path, class: 'dropdown-item'%></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete}, class: 'dropdown-item'%></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header-upper">
  <div class="header-left">
    <%= image_tag 'logo.png', class: "header-logo" %>
      <%# <%= link_to (root_path), class: "header-title" do %>
        <%# MW %>
      <%# <% end %>
  </div>

  <div class="header-center">
    <div class="header-center-title" id="header_home">
      <%= @page_title %>
      <% if @room.present? %>
        <div class="header-center-content">
          <div class="room-nane">
            <%= @room.name %>
          </div>&nbsp;
          <div class="room-day">
            <%= @room.wedding_day.strftime('%Y.%m.%d') %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class="header-right">
    <% if @room.present? %>
      <div class="btn-group dropstart">
        <button class="btn btn-outline-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
          </svg>
        </button>
        <ul class="dropdown-menu">
          <% if @room.host_id == current_user.id %>
            <li class="dropdown-item">key：<%= @room.room_key %></li>
            <li><%= link_to 'Room削除', room_path(@room), data: { turbo_method: :delete, turbo_confirm: "Room削除してよろしいですか？"}, class: "dropdown-item" %></li>
          <% else %>
            <li><%= link_to 'Room退出', exit_room_path(@room), data: { turbo_method: :delete, turbo_confirm: "退出してよろしいですか？" }, class: "dropdown-item" %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <% if @page_title == "Favorite" %>
      <%= link_to(user_download_favorites_path(current_user), class: "link-btn") do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
          <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
          <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
        </svg>
        <p class="download-text">
          All
        </p>
      <% end %>
    <% end %>
  </div>
</div>

<div class="header-bottom">
  <div class="enter-room">
    <%= form_with(url: search_rooms_path, local: true, method: :get, class: "col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3") do |form| %>
      <%= form.text_field :room_key, placeholder: "Room_Keyを入力", class: "form-control" %>
      <%# <%= form.submit "参加", class: "search-btn" %>
    <% end %>
  </div>
</div>