config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :rooms, only: [:new, :create, :destroy] do
    resources :posts, only: [:index, :new, :create] do
      member do
        get 'show_image/:index', to: 'posts#show_image', as: 'show_image'
        get 'show_video/:index', to: 'posts#show_video', as: 'show_video'
        delete 'show_image/:index/image', to: 'posts#destroy_image', as: 'destroy_image'
        delete 'show_video/:index/video', to: 'posts#destroy_video', as: 'destroy_video'
        post 'add_favorite/:index/:media_type', to: 'favorites#create', as: 'add_favorite'
        delete 'remove_favorite/:index/:media_type', to: 'favorites#destroy', as: 'remove_favorite'
      end
    end
    member do
      delete 'exit'
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: :show do
    get '/download_favorites.zip', to: 'favorites#download_all', as: 'download_favorites'
    resources :favorites, only: :index
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_many_attached :images
  has_many_attached :videos
  has_many :favorites, dependent: :destroy

  validate :images_contain_only_images
  validate :videos_contain_only_videos
  validates :images, presence: true, unless: :was_attached?
  
  def favorited_by?(user, post, media_id, media_type)
    favorites.where(user_id: user.id, post_id: post.id, media_id: media_id, media_type: media_type).exists?
  end

  def was_attached?
    self.videos.attached?
  end

  def images_contain_only_images
    if images.attached?
      images.each do |image|
        unless image.content_type.starts_with?('image/')
          errors.add(:images, '写真フォームには写真のみ投稿できます')
        end
      end
    end
  end

  def videos_contain_only_videos
    if videos.attached?
      videos.each do |video|
        unless video.content_type.starts_with?('video/')
          errors.add(:videos, '動画フォームには動画のみ投稿できます')
        end
      end
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_room, only: [:index, :new, :create, :show_image, :show_video, :destroy_image, :destroy_video]
  before_action :set_post, only: [:show_image, :show_video, :destroy_image, :destroy_video]
  before_action :set_image, only: [:show_image, :destroy_image]
  before_action :set_video, only: [:show_video, :destroy_video]
  before_action :authenticate_user!
  def index
    @posts = @room.posts.includes(:user).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = @room.posts.new(post_params)
    if @post.save
      redirect_to room_posts_path(@room)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show_image
    @media_type = 'image'
  end

  def show_video
    @media_type = 'video'
  end

  def destroy_image
    if @media
      favorite = current_user.favorites.find_by(post_id: @post.id, media_id: @image_index, media_type: 'image')
      favorite.destroy if favorite
      @media.purge
      
      @post.images.reload
      if @post.images.empty? && @post.videos.empty?
        @post.destroy
      end
    end
    redirect_to room_posts_path(@room)
  end

  def destroy_video
    if @media
      favorite = current_user.favorites.find_by(post_id: @post.id, media_id: @video_index, media_type: 'video')
      favorite.destroy if favorite
      @media.purge
      
      @post.videos.reload
      if @post.videos.empty? && @post.images.empty?
        @post.destroy
      end
    end
    redirect_to room_posts_path(@room)
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_post
    @post = @room.posts.find(params[:id])
  end

  def set_image
    @image_index = params[:index].to_i
    @media = @post.images[@image_index]
  end

  def set_video
    @video_index = params[:index].to_i
    @media = @post.videos[@video_index]
  end

  def post_params
    params.require(:post).permit(images: [], videos: []).merge(user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<% if post.images.attached? || post.videos.attached? %>  
  <% if post.images.attached? %>
    <% post.images.each.with_index do |image, index| %>
      <div class="post">
        <%= link_to show_image_room_post_path(@room, post, index: index) do %>
          <%= image_tag image.variant(resize_to_fill: [300, 300, gravity: 'center']).processed, class: 'img-thumbnail' %>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <% if post.videos.attached? %>
    <% post.videos.each.with_index do |video, index| %>
      <div class="post">
        <%= link_to show_video_room_post_path(@room, post, index: index) do %>
          <div class="video-background">
            <% if video.representable? %>
             <%= image_tag video.representation(resize_to_fill: [300, 300, gravity: 'center']).processed, class: 'img-thumbnail' %>
              <%# <%= video_tag rails_blob_path(video, disposition: :attachment), class: 'img-thumbnail' %>
            <% end %>
          </div>
          <div class="video-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="block" class="bi bi-caret-right-square-fill" viewBox="0 0 16 16">
              <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm5.5 10a.5.5 0 0 0 .832.374l4.5-4a.5.5 0 0 0 0-.748l-4.5-4A.5.5 0 0 0 5.5 4v8z"/>
            </svg>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_side-bar.html.erb
<div class="side-bar-header">
  <div class="side-bar-header-upper">
    <%= link_to (root_path), class: "title" do %>
    <h3>MyWedding</h3>
    <% end %>
  </div>
  <hr>
</div>
<div class="rooms">
  <% if user_signed_in? %>
    <div class="rooom-cintents">
      <%= link_to (user_path(current_user.id)), class: 'link-btn' do %>
      <div class="side-category">
        <div class="category-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
            <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z" />
          </svg>
        </div>
        <div class="category-text">
          Home
        </div>
      </div>
      <% end %>
      <%= link_to(new_room_path, class: 'link-btn') do %>
      <div class="side-category">
        <div class="category-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 16 16">
            <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
          </svg>
        </div>
        <div class="category-text">
          New
        </div>
      </div>
      <% end %>
      <div class="side-category" id="room_nav">
        <div class="category-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-box" viewBox="0 0 16 16">
            <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
          </svg>
        </div>
        <div class="category-text">
          Room
        </div>
      </div>
        <div class="now-room hidden" id="now_room">
          <% current_user.rooms.each do |room| %>
            <div class="pull-down-lists">
              <%= link_to(room_posts_path(room), class: 'link-btn') do %>
              <div class="list">
                <div class="room-name">
                  <%= room.name %>
                </div>
              </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <div class="form-room">
        <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
        <div class="form-room_path">
          <div class="col-auto-room">
            <%= form.text_field :room_key, placeholder: "Room_keyを入力", class: "form-control" %>
          </div>
          <div class="d-grid gap-2">
            <%= form.submit "参加", class: "btn btn-outline-secondary" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <hr>
    <div class="side-category" id="user_nav">
      <div class="user-acount" >
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
          <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg>
        <%= current_user.name %>
      </div>
    </div>
    <div class="pull-down-lists hidden" id="logout">
      <div class="list">
        <div class="sign-out-btn">
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete}, class: "link-btn" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side-bar" %>
  </div>
  <div class="side-space"></div>
  <%# スマホ表示 %>
  <div class="header-mobile">
    <%= render 'shared/header'%>
  </div>

  <div class="main-contents">
    <div class="main-header">
      <div class="main-header-upper">
        <div class="main-header-upper_left">
          <div class="title-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-box" viewBox="0 0 16 16">
              <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
            </svg>
          </div>
          <div class="title-text">
            <%= @room.name %>&emsp;<%= @room.wedding_day.strftime('%Y.%m.%d') %>
          </div>
        </div>
        <div class="delete-contents" id="delete_nav">
          <div class="delete-lists">
            <div class="delete-btn hidden" id="delete_btn">
              <% if @room.host_id == current_user.id %>
                <div class="header-list">
                  Key：<%= @room.room_key %>
                </div>
                <div class="header-list">
                  <%= link_to 'ルーム削除', room_path(@room), data: { turbo_method: :delete, turbo_confirm: "ルーム削除してよろしいですか？"}, class: "link-btn-header" %>
                </div>
              <% else %>
                <div class="header-list">
                  <%= link_to 'ルーム退出', exit_room_path(@room), data: { turbo_method: :delete, turbo_confirm: "退出してよろしいですか？" }, class: "link-btn-header" %>
                </div>
              <% end %>
            </div>
            <div class="delete-list-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
              </svg>
            </div>
          </div>
        </div>
      </div>
      <hr>
    </div>
       
    <div class="posts">
      <%= render partial: 'post', collection: @posts %>
    </div>


    <%# 投稿ボタン %>
    <%= link_to(new_room_post_path, class: 'post-btn') do %>
      <button type="button" class="btn btn-outline-primary">
        <div class="post-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
          </svg>
        </div>
      </button>
    <% end %>
  </div>
  <div class="footer-mobile">
    <%= render 'shared/footer'%>
  </div>
</div>

app/views/posts/new.html.erb
<body class="d-flex align-items-center py-4 bg-body-tertiary">
  <div class="form-main-wrap" >
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>
  <main class="form-signin w-100 m-auto">
    <div class="header-title">
      <%# <%= image_tag 'mywedding'%>
      <div class="side-bar-header-upper">
        <h3><%= link_to 'MyWedding', room_posts_path(@room), class: "root-title" %></h3>
      </div>
    </div>
  <%= form_with model: [@room, @post], id: 'new_post', local: true, class: 'registration-main' do |f| %>

  <div class='form-wrap'>  
    <div class='form-header'>
      <h1 class="form-header-text">
        New Post
      </h1>
    </div>
  
  <%= render 'shared/error_messages', model: f.object %>

    <div class="mb-3">
      <div class='form-text-wrap'>
        <label class="form-label"><span class="form-label-post">写真</span></label>
      </div>
      <i class="fas fa-camera"></i>
      <%= f.file_field :images, name: 'post[images][]', multiple: true, class:"form-control" %>
    </div>

    <div class="mb-3">
      <div class='form-text-wrap'>
        <label class="form-label"><span class="form-label-post">動画</span></label>
      </div>
      <%= f.file_field :videos, name: 'post[videos][]', multiple: true, class:"form-control" %>
    </div>

   <%# <div id="previews"></div> %>

  <div class="form-send-btn">
    <%= button_tag(type: 'submit', class: 'btn btn-primary w-100 py-2') do %>
      Post
    <% end %>
  </div>
</div>
<% end %>

app/views/posts/show_image.html.erb
<div class="wrapper">
  <div class="show-cover">
    <div class="header-title">
      <div class="side-bar-header-upper">
        <h3><%= link_to 'MyWedding', room_posts_path(@room), class: "root-title" %></h3>
      </div>
    </div>
 
    <div class="show-main">
      <div class="card" style="width: 26rem;">
        <%= image_tag @media,class: "card-img-top" %>
        <div class="card-body">
          <div class="card-header-wrap">
            <%# お気に入りボタン %>
            <div class="card-header-left">
              <span id="like-btn<%= @media.id %>">
                <%= render partial: "favorites/favorite", locals: { room: @room, post: @post, media_id: @image_index, media_type: @media_type} %>
              </span>
              <div class="dl_media_btn">
                <%= link_to rails_blob_path(@media, disposition: "attachment"), class: "link-btn" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                    <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                    <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                  </svg>
                <% end %>
              </div>
            </div>
            <div class="card-header-right">
              <div class="post-delet-btn">
                <% if @post.user_id == current_user.id %>
                  <%= link_to destroy_image_room_post_path(@room, @post, params[:index]), data: { turbo_method: :delete, turbo_confirm: "写真を削除してよろしいですか？"} do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                      <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                    </svg>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <p class="card-text">
              Thank you <%= current_user.name if @post.user_id == current_user.id %> for coming to our wedding.
          </p>
        
          <div class="show_bottom_btn">
            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show_video.html.erb
<div class="wrapper">
  <div class="show-cover">

    <div class="header-title">
      <div class="side-bar-header-upper">
        <h3><%= link_to 'MyWedding', room_posts_path(@room), class: "root-title" %></h3>
      </div>
    </div>

    <div class="show-main">
      <div class="card" style="width: 26rem;">
        <%= video_tag rails_blob_path(@media, disposition: :attachment), playsinline: true, autoplay: true, muted: true, controls: true, class: "card-img-top" %>
        <div class="card-body">
          <div class="card-header-wrap">
            <div class="card-header-left">
              <%# お気に入りボタン %>
              <span id="like-btn<%= @media.id %>">
                <%= render partial: "favorites/favorite", locals: { room: @room, post: @post, media_id: @video_index, media_type: @media_type} %>
              </span>
              <div class="dl_media_btn">
                <%= link_to rails_blob_path(@media, disposition: "attachment"), class: "link-btn" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                    <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                    <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                  </svg>
                <% end %>
              </div>
            </div>
            
            <div class="card-header-right">
              <div class="post-delet-btn">
                <% if @post.user_id == current_user.id %>
                  <%= link_to destroy_video_room_post_path(@room, @post, params[:index]), data: { turbo_method: :delete, turbo_confirm: "動画を削除してよろしいですか？"} do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                      <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                    </svg>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <p class="card-text">
            Thank you for <%= current_user.name if @post.user_id == current_user.id %> coming to our wedding.
          </p>
        
          <div class="show_bottom_btn">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>